### ISSUE TITLE
Dragging totem skills from TotemTimers to action bar gives me rank 1 totems

### ISSUE THREAD

**Issue by GrahamSayers** [Xianghar/TotemTimers_Classic#6]
Hi, I'm enjoying TotemTimers in TBC Classic. I use the flyout totem menus to keep my screen clean and drag totems onto my action bars when I need them for a fight. However, when I do this I end up with Rank 1 totem skill on my action bar. Seems you should instead get a max rank totem when you do this. If I just click the totem from the totemtimers bar it does give me the max rank. It's only when I try to drag it to another bar that I end up with rank 1. Thanks!

**Comment by Xianghar** [comment]
It's not an error. Dragging totems is only for reordering them, not for putting them on your action bars. The spells need to be rank 1 for reordering to work.
Setting up totems for a fight is what the right click to assign them to the timer buttons is for.
